prob_035: prob_035.o primes.o
	gcc -Wall -ansi -pedantic-errors *.o -o prob_035 -lm -O3

primes.o: primes.c primes.h
	gcc -Wall -ansi -pedantic-errors primes.c -c -O3

prob_035.o: prob_035.c
	gcc -Wall -ansi -pedantic-errors prob_035.c -c -O3
